### PR TITLE
remove obsolete fixture that is causing rake db:seed to fail

### PR DESCRIPTION
**Pull request by mfrederickson**

### CODE REVIEW

**Comment by mfrederickson** [comment]
rake test shows
```
mfrederickson@artemis2:~/projects/rol$ rake test
Run options: --seed 51691

# Running:

....................................................................unknown OID 705: failed to recognize type of 'id'. It will be treated as String.
.........................................................................................................................................................................F

Finished in 14.471514s, 16.4461 runs/s, 70.3451 assertions/s.

  1) Failure:
UsersLoginTest#test_login_with_invalid_information [/mnt/683fd734-8323-4ac0-a2ba-1436ff10f137/data2/projects/rol/test/integration/users_login_test.rb:14]:
expecting <"sessions/new"> but rendering with <[]>

238 runs, 1018 assertions, 1 failures, 0 errors, 0 skips
```

The OID problem is mentioned here https://gist.github.com/otobrglez/6bc6c4f1c27abb8d1f53.

Need guidance on whether you want these resolved for this PR.

**Comment by tescher** [comment]
Sure, you can fix the ::text is as well in this PR. Thanks!

**Comment by mfrederickson** [comment]
I'm not sure how to go about finding where it is...

**Comment by tescher** [comment]
Hmm, me neither

Tim Escher
tim@eschers.com
608-432-5799

**Comment by tescher** [comment]
I think this is moot now that the model stubs have been left in place.

**Pull request closed without merging**
